# Generated by Django 4.1 on 2022-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_groupmessagesmodel_message_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagesmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessagesmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessagesmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmessagesmodel',
            name='attachments',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='groupmessagesmodel',
            name='message_format',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='Text', max_length=15),
        ),
        migrations.AlterField(
            model_name='privatemessagesmodel',
            name='attachments',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='privatemessagesmodel',
            name='message_format',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='Text', max_length=15),
        ),
    ]
