# Generated by Django 4.1 on 2022-09-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_groupinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privategroupmessagesmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
